### PR TITLE
[Support] Django2.2

### LINKED ISSUE #78: [django] Add support for django 2.2
Add support for django 2.2

### PR DESCRIPTION
**Pull request by DaffyTheDuck**
[Fix #78] Added support of django2.2 and updated djangorestframework

### CODE REVIEW

**Review by atb00ker — COMMENTED** [review]
Great work @IAmAMissingColon 

The travis tests might be failing for irrelevant reasons but just 
to make sure, did you run the tests on your machine `./runtests.py` ?

Also, a small nit-pick.
The commit message should be `[requirements] Added Support For Django2.2` and not `[django-ipam] Added Support For Django2.2`, you can change it with the help of the command `git commit --amend`.

**Comment by DaffyTheDuck** [comment]
> Great work @IAmAMissingColon
> 
> The travis tests might be failing for irrelevant reasons but just
> to make sure, did you run the tests on your machine `./runtests.py` ?
> 
> Also, a small nit-pick.
> The commit message should be `[requirements] Added Support For Django2.2` and not `[django-ipam] Added Support For Django2.2`, you can change it with the help of the command `git commit --amend`.

`./runtests.py` is running without any error 😄

**Comment by atb00ker** [comment]
> Added support of django2.2 and updated djangorestframework

I don't see the change for djangorestframework!

**Comment by DaffyTheDuck** [comment]
> > Added support of django2.2 and updated djangorestframework
> 
> I don't see the change for djangorestframework!

Actually, In the first commit I changed the djangorestframework vesrion, but later I decided to cancel it :sweat_smile: 

Should I change it again ?
Or just change the commit message ?

**Review by atb00ker — APPROVED** [review]

**Comment by DaffyTheDuck** [comment]
Thank You Sir :smiley:

**Review by nemesifier — APPROVED** [review]

**Pull request merged**
