### PR TITLE
[qa] BaseSerializer Imported/Implemented

### LINKED ISSUE #53: Import BaseSerializer from openwisp-utils
**Reserved for GCI**

- Import DRF base serializer from openwisp-utils (implemented in https://github.com/openwisp/openwisp-utils/issues/12)
- remove the `validate` method from the serializers of django-ipam

### PR DESCRIPTION
**Pull request by EdgeKing810**
Imported BaseSerializer from https://github.com/openwisp/openwisp-utils/pull/13/ and removed validate method in serializers.py. Anything more I need to do?

closes #53

### CODE REVIEW

**Comment by EdgeKing810** [comment]
Any help on how to get the coverage back to 100% again? :/

**Comment by EdgeKing810** [comment]
Now I am getting an error in the travis build. Can someone help me to fix that error and give me some instructions on how to further proceed? Thanks. I'm relatively new to coverage things with python...

**Comment by EdgeKing810** [comment]
After a loooong tiring day, I managed to do it. Please let me know of other things that I need to fix or improvements that I need to do.

**Review by nemesifier — CHANGES_REQUESTED** [review]
You clearly have not understood what you need to do.

Read again the issue description here: https://github.com/openwisp/django-ipam/issues/53

You need to import `ValidatedModelSerializer` from openwisp-utils, use it as the base serializer for the serializers in this module and remove the `validate` method.

Please start from scratch.

**Comment by EdgeKing810** [comment]
I'm still not really understanding what to do... Could you guide me a little more please?

**Comment by EdgeKing810** [comment]
So... as far as I understood, all the files in django-ipam remains the same. Just in django_ipam/api/serializers.py, we pass ValidatedModelSerializer as the parameter then remove validate methods from other serializers files including this one. So to start with, how do I import ValidateModelSerializer from openwisp-utils?

Let me know if my understanding is correct.

**Comment by EdgeKing810** [comment]
I don't know if I did it correctly this time. Please let me know...

**Review by nemesifier — CHANGES_REQUESTED** [review]
Ok, that's better, let's change the commit message to something which makes more sense, the indication in the original issue was a bit vague:

```
[serializers] Imported ValidatedModelSerializer from openwisp-utils #53

Closes #53
```

**Comment by EdgeKing810** [comment]
I didn't know that's all that needed to be done. Also, I was trying to keep the first line of the commit message short so as that it is readable without expanding. It's sure better now though.

**Review by nemesifier — APPROVED** [review]
Short is good, but sometimes not possible. The guideline to keep in mind is readable, understandable and compact.

Good job :+1:

**Pull request merged**
