### PR TITLE
[models] NetworkField: fix conversion of None values

### LINKED ISSUE #94: Getting errors when running a migration for a NetworkField on PostgreSQL
I'm getting errors when running a migration for a NetworkField on PostgreSQL:

```
  File "/home/openwisp/openwisp/.venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type cidr: "None"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    main()
  File "manage.py", line 23, in main
    execute_from_command_line(sys.argv)
  File "/home/openwisp/openwisp/.venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/openwisp/openwisp/.venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/openwisp/openwisp/.venv/lib/python3.5/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/openwisp/openwisp/.venv/lib/python3.5/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/home/openwisp/openwisp/.venv/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    fake_initial=fake_initial,
  File "/home/openwisp/openwisp/.venv/lib/python3.5/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/openwisp/openwisp/.venv/lib/python3.5/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/openwisp/openwisp/.venv/lib/python3.5/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/openwisp/openwisp/.venv/lib/python3.5/site-packages/django/db/migrations/migration.py", line 122, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/openwisp/openwisp/.venv/lib/python3.5/site-packages/django/db/migrations/operations/fields.py", line 84, in database_forwards
    field,
  File "/home/openwisp/openwisp/.venv/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 437, in add_field
    self.execute(sql, params)
  File "/home/openwisp/openwisp/.venv/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 133, in execute
    cursor.execute(sql, params)
  File "/home/openwisp/openwisp/.venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/openwisp/openwisp/.venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/openwisp/openwisp/.venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/openwisp/openwisp/.venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/openwisp/openwisp/.venv/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/openwisp/openwisp/.venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: invalid input syntax for type cidr: "None"
```
I tried setting `blank=True, null=True` and tried setting `default="192.168.10/24""` but that didn't help.

I would be grateful for any hints.

### PR DESCRIPTION
**Pull request by okraits**
Fixes #94

### CODE REVIEW

**Review by nemesifier — COMMENTED** [review]
@okraits could you modify the first line of the commit message as follows please?

```
[models] NetworkField: Fix conversion of None values #94
```

**Comment by okraits** [comment]
@nemesisdesign Should I add a test for that?

**Review by nemesifier — COMMENTED** [review]
@okraits that would be great! Can you?

**Comment by okraits** [comment]
> @okraits that would be great! Can you?

I will try to come up with a test later today.

**Review by nemesifier — APPROVED** [review]

**Comment by nemesifier** [comment]
I'm merging since it's just one line but if you do find a way to test please send it

**Comment by okraits** [comment]
Ok - I just don't have the time to look into this now :cry:

**Pull request merged**
