### PR TITLE
[admin] Improved subnet import page

### LINKED ISSUE #38: [admin] Improvement of the subnet import page
The subnet csv import page `/admin/django_ipam/subnet/import/` is missing some common elements which most/all other pages have:

* the "session management area": `Welcome, user. Change password / Log out`
* the breadcrumbs navigation: `Home › IPAM › Ip addresss › Import subnet`
* a `Back` or `Cancel` button.

### PR DESCRIPTION
**Pull request by anurag-ks**
Implements and closes #38

### CODE REVIEW

**Comment by nemesifier** [comment]
@okraits would you like to help me reviewing this?

**Comment by okraits** [comment]
* columns `Name` and `Description` were added to the index pages :+1: 
* the "session management area" (Welcome, user. Change password / Log out) is visible on the import page :+1: 
* the breadcrumbs navigation is visible on the import page :+1: 
* the import page has  a `Cancel` button :+1: 

New annotations:
* In `/django_ipam` IMO `Subnets` should be the first link and `Ip Addresses` should be the second
* The plural `Ip addresss` should be `Ip addresses` - I think this is django's fault
* Is there a difference between `Home > Subnets > Import` and `Home > Subnets > x.x.x.x/x > Import`?

**Comment by anurag-ks** [comment]
Thanks for the review @okraits ,

-  We can do something like this to reorder the models under the admin page, the models are sorted according to their `verbose_name_plural` value under `Meta`. 



- `Is there a difference between Home > Subnets > Import and Home > Subnets > x.x.x.x/x > Import?` - There is no difference actually, the csv import format requires the user to specify the subnet as well, so I think we can remove the `import` button from this page - `Home > Subnets > x.x.x.x/x ` (change view) and keep a single `import` button on the change list view.

**Comment by okraits** [comment]
* Does an import always create a new subnet or is it also possible to only import ip addresses into an existing subnet? If the former is true, then the `Import` button should only be on the subnets index page,  if the latter is true, then there needs to be an `Import` button also on the subnet change page.

* I think the text for the import button on the subnets index page should be `Import Subnet/IP Addresses` - plural.

**Comment by nemesifier** [comment]
@okraits it should be possible to import addresses into an existing subnet, @anurag-ks do you confirm?

I wouldn't touch the PR further, it's good enough for now.
The admin lists available models in alphabetical order, we shouldn't mess with that.
In the near feature we will introduce a dashboard and a navigation menu, at the moment our users will have to be satisfied with what django is able to give us with minimum effort.

**Comment by anurag-ks** [comment]
If the subnet already exists, the system would ignore it and add the IP addresses. If the subnet is not present on the system, it will create it and then add the IP addresses.

**Comment by anurag-ks** [comment]
I will add this in an improved manner to the README as well. I will be sending a PR later.

**Review by nemesifier — APPROVED** [review]
@anurag-ks `usertools` is redundant.. but I fixed it myself (committing to master). While fixing this small issue I noticed many other small issues which I fixed. Please see my commits on master (so you can avoid this issues in the future) and ask questions if you have doubts.

**Comment by nemesifier** [comment]
@okraits I tried to improve the wording, check if now is better and let us know

**Comment by okraits** [comment]
@nemesisdesign I have to be picky: why `Import Subnet` but `Export Subnet Data`?

**Comment by nemesifier** [comment]
@okraits right, which one you like most? :-)

**Comment by okraits** [comment]
@nemesisdesign I prefer `Import Subnet` and `Export Subnet` because it should be clear that Import/Export is about data anyway :-)

**Comment by nemesifier** [comment]
@okraits ok I second that, could you edit here on github and send a PR please? I'm overloaded with other PR and issues to review/merge/implement

**Comment by nemesifier** [comment]
@okraits ok I second that, could you edit here on github and send a PR please? I'm overloaded with other PR and issues to review/merge/implement

**Comment by okraits** [comment]
@nemesisdesign Done with #45 :sunglasses:

**Pull request merged**
