### PR TITLE
[enchancement] Added sqlite version check

### PR DESCRIPTION
**Pull request by waleko**
Resolves issue #81 

Added a sqlite version check to prevent segmentation fault being raised.

### CODE REVIEW

**Review by nemesifier — COMMENTED** [review]
This change assumes sqlite will be used, but the app/library could be used with mysql or postgresql as well.

**Comment by atb00ker** [comment]
I think a relevant fix here would be changing the travis version to fix the issue! (Like using `bionic`)

**Comment by nemesifier** [comment]
@atb00ker https://github.com/openwisp/django-ipam/blob/master/.travis.yml#L3

**Comment by atb00ker** [comment]
Oh, is this solved because the issue is closed but the last PR also had this `Segmentation fault` problem: https://travis-ci.org/openwisp/django-ipam/jobs/626999210?utm_medium=notification&utm_source=github_status

**Comment by nemesifier** [comment]
@atb00ker seems I merged both 12 days ago, on the same day. So the build was performed before I merged https://github.com/openwisp/django-ipam/pull/80 which contains the change to `bionic`.

**Pull request closed without merging**
